feat(Tag): modify boderColor and add ellipsis for Tag
oceanbase/oceanbase-design pull request #113
Opened 2023-08-31 09:39 UTC by wdyea-ya

## Summary
弱化 Tag 组件的边框颜色并增加标签内容溢出自动显示省略号功能

## Solution Description
通过调整透明度来弱化边框颜色
![image](https://github.com/oceanbase/oceanbase-design/assets/62171869/bcf20119-ced2-4b1c-93e8-95b8871c6883)
![image](https://github.com/oceanbase/oceanbase-design/assets/62171869/982085f7-9882-4b6d-928c-bcd94bba243e)
![image](https://github.com/oceanbase/oceanbase-design/assets/62171869/d9917d4c-7ec8-4f7a-bcc2-7285fd79b36c)
![image](https://github.com/oceanbase/oceanbase-design/assets/62171869/531380a6-6fd8-4220-b8fc-c59334b748ff)

2023-08-31 09:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oceanbase/oceanbase-design?pullRequest=113) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/oceanbase/oceanbase-design?pullRequest=113) before we can accept your contribution.<br/><hr/>**wdy01684395** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oceanbase/oceanbase-design?pullRequest=113) it.</sub>

2023-09-20 07:00 UTC, dengfuping requested changes
另外，CI 是失败的，也需要修复下

2023-09-20 07:00 UTC, dengfuping commented on packages/design/src/select/index.tsx
> +import React, {useContext} from 'react';
需要使用 prettier 格式化代码，VSCode 下 `Command + S` 保存文件就可以触发格式化。

2023-09-20 07:00 UTC, dengfuping commented on packages/design/src/tag/demo/basic.tsx
> +        <a href="https://github.com/ant-design/ant-design/issues/1862">Link</a>
链接改为 `https://github.com/oceanbase/oceanbase-design` 吧

2023-09-20 07:00 UTC, dengfuping commented on packages/design/src/tag/demo/status.tsx
> +
多了一个空行

2023-09-20 07:00 UTC, dengfuping commented on packages/design/src/tag/index.tsx
> +            [`${prefixCls}-ellipsis`]: !!width
最大宽度 width 意义不是很大，实际场景一般是取决于容器宽度，不是一个固定值。如果能根据容器宽度自适应 ellipsis 是最好的。

2023-09-20 07:00 UTC, dengfuping commented on packages/design/src/tag/style/index.ts
> +            borderColor: token[`color${capitalizedCssVariableType}Border`] + 66
- 只需要定制 `borderColor` 样式，文字颜色不需要定制，会根据 token 自动生效。
- 不需要 `cssVariableType` 参数，只要设置好 `status => borderColor` 的映射关系就行:
```ts
const borderColorMap = {
  success: token.colorSuccessBorder,
  processing: token.colorInfoBorder,
  error: token.colorErrorBorder,
  warning: token.colorWarningBorder,
};
```

2023-09-20 07:00 UTC, dengfuping commented on packages/design/src/tag/style/index.ts
> +            color: textColor,
- 文字颜色不需要定制

2023-09-20 07:00 UTC, dengfuping commented on packages/design/src/tag/style/index.ts
> +        });
这些 token 都不需要定制，去掉即可

2023-09-20 07:00 UTC, dengfuping commented on packages/design/src/tag/style/index.ts
> +            [`&-checkable`]: {
- `&-ellipsis` 可以作为 tag 的默认样式，看看超出容器宽度是否会自动 ellipsis
- `&-checkable` 的样式不需要定制

2023-09-20 07:00 UTC, dengfuping commented on packages/design/src/tag/style/index.ts
> +            color: colorTextLabel,
不需要定制字体颜色

2023-09-20 07:00 UTC, dengfuping commented on packages/design/src/tag/demo/select.tsx
> +        <Tag
- Select 和 Tag 组合使用的 demo 放 Select 组件下吧
- Tag 下新增一个无边框的 demo https://ant-design.antgroup.com/components/tag-cn#tag-demo-borderless

2023-09-20 07:00 UTC, dengfuping commented on packages/design/src/tag/demo/select.tsx
> +            style={{ marginRight: 3 }}
Tag 之间的间距为 8，应该去掉 `marginRight` 样式设置

2023-09-20 07:00 UTC, dengfuping commented on packages/design/src/select/style/index.ts
> +                border:  `1px solid ${token.colorBorder}66`,
封装一个 getTagBorderColor 的工具函数吧，将分散的逻辑统一维护起来:
```ts
import { TinyColor } from '@ctrl/tinycolor';

const getTagBorderColor = (color: string) => {
  return new TinyColor(color).setAlpha(0.66).toHexString();
};

borderColor: getTagBorderColor(token.colorBorder);
```

2023-10-13 09:30 UTC, wdyea-ya commented on packages/design/src/select/index.tsx
> +import React, {useContext} from 'react';
cr 问题已修复

2023-10-26 06:09 UTC, wdyea-ya commented on packages/design/src/tag/demo/basic.tsx
> +        <a href="https://github.com/ant-design/ant-design/issues/1862">Link</a>
链接已经调整为 https://github.com/oceanbase/oceanbase-design

2023-10-26 06:12 UTC, wdyea-ya commented on packages/design/src/tag/demo/status.tsx
> +
> 多了一个空行

status.tsx 文件开头的空行已经去掉

2023-10-26 06:29 UTC, wdyea-ya commented on packages/design/src/tag/index.tsx
> +            [`${prefixCls}-ellipsis`]: !!width
可以通过容器宽度自动ellipsis, 增加了一个ellipsis参数，默认为true

2023-10-27 09:17 UTC, dengfuping approved these changes

2023-10-27 09:21 UTC, merged