feat: add sync other npm
oceanbase/oceanbase-design pull request #19
Opened 2023-07-12 14:30 UTC by any1024

ref: #17

2023-07-12 14:35 UTC, any1024 commented on package.json
> +    "execa": "^5.1.1",
Execa 5. * Use `require` get  pkg , but execa latest 7. * Use`import` .
 `execa@7. *` Unable to run successfully under ts-node, I tried to modify some configurations. But it has never been successful.

2023-07-13 03:36 UTC, dengfuping approved these changes

2023-07-13 03:36 UTC, dengfuping commented on package.json
> +    "sync:other-npm": "node -e 'require(\"./scripts/sync-tnpm-with-cnpm\")()'",
- `sync-cnpm-with-tnpm` => `sync-cnpm-and-tnpm`
- Add `postpublish` script to execute `sync:other-npm`

2023-07-13 03:38 UTC, dengfuping requested changes
Request changes

2023-07-13 13:30 UTC, dengfuping requested changes
- should fix conflicts

2023-07-13 17:13 UTC, any1024 commented
@dengfuping Help me see the reason for Preview Start Error

2023-07-14 02:52 UTC, dengfuping commented
> @dengfuping Help me see the reason for Preview Start Fail

- I will fix this problem later. This PR could be merged.

2023-07-14 02:52 UTC, merged