fix(Tooltip):should hide when tooltip title is none
oceanbase/oceanbase-design pull request #405
Opened 2024-01-09 06:23 UTC by linhf123

### 📦 Modified package

- [x] @oceanbase/design
- [ ] @oceanbase/ui
- [ ] @oceanbase/icons
- [ ] @oceanbase/charts
- [ ] @oceanbase/util
- [ ] @oceanbase/codemod
- [ ] Other (about what?)

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution
二封 Tooltip 时完全接管了 open，antd 内部 noTitle 时不调用 openChange 导致显示异常，同步了下 antd 的 noTitle 逻辑处理了下 innerOpen  取值

![image](https://github.com/oceanbase/oceanbase-design/assets/32009993/dc54575f-ce15-4eaf-8324-ba822afa2993)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     should hide when tooltip title is none      |
| 🇨🇳 Chinese |    当 tooltip title 不存在时应该不显示 tooltip       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Tests is updated/provided or not needed
- [ ] Changelog is provided or not needed

2024-01-09 06:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oceanbase/oceanbase-design?pullRequest=405) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/oceanbase/oceanbase-design?pullRequest=405) before we can accept your contribution.<br/><hr/>**linhf123** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oceanbase/oceanbase-design?pullRequest=405) it.</sub>

2024-01-10 11:58 UTC, dengfuping requested changes

2024-01-10 11:58 UTC, dengfuping commented on packages/design/src/tooltip/index.tsx
> -    }, [open, visible]);
单测挂了，这段状态维护逻辑应该保留？

2024-01-11 02:09 UTC, linhf123 commented on packages/design/src/tooltip/index.tsx
> -    }, [open, visible]);
test 目录下新加了一个 util 没有运行测试用例报错了，我加个规则绕过一下

![image](https://github.com/oceanbase/oceanbase-design/assets/32009993/281b4eb7-65a2-4d68-b047-5f559f534ac8)

2024-01-11 03:19 UTC, linhf123 commented on packages/design/src/tooltip/index.tsx
> -    }, [open, visible]);
按照优先级来看，并不需要上面那段逻辑来同步 innerOpen，所以我直接去掉了
![image](https://github.com/oceanbase/oceanbase-design/assets/32009993/24afee53-f662-4d0b-8c74-ee1b26449f90)

2024-01-12 02:16 UTC, dengfuping commented on packages/design/src/tooltip/index.tsx
> -    }, [open, visible]);
单测 util 可以统一放 `tests/util.ts` 目录

2024-01-12 02:19 UTC, merged