feat(Tooltip): Tooltip support for closeIcon and onClose
oceanbase/oceanbase-design pull request #63
Opened 2023-07-31 17:49 UTC by linhf123

ref: #49 

# Demo
![image](https://github.com/oceanbase/oceanbase-design/assets/32009993/76b3380b-9cf5-456f-8f15-b5dd26228b22)
![image](https://github.com/oceanbase/oceanbase-design/assets/32009993/c1ef7f6e-f07b-4507-a8a4-b606b18bdbe2)
![image](https://github.com/oceanbase/oceanbase-design/assets/32009993/abc5989f-adba-42e4-812d-3478ce8f7399)

# API
![image](https://github.com/oceanbase/oceanbase-design/assets/32009993/c786a3b0-15f3-40dd-9768-19a23895eaaf)

2023-08-01 03:21 UTC, dengfuping requested changes

2023-08-01 03:21 UTC, dengfuping commented on packages/design/src/tooltip/index.tsx
> +      {closeTitle}
- 可以不用扩展 `closeTitle` 这个属性，我给的示例可能有误导性。不过实现的时候需要考虑下，内容换行的时候 `closeIcon` 如何处理。

![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/82725d42-dd2f-4697-bb7e-4e1ef95b0399)

2023-08-01 03:21 UTC, dengfuping commented on packages/design/src/tooltip/index.md
> +| onClose | 关闭时的回调（可通过 e.preventDefault() 来阻止默认行为） | (e) => void | - | - |
可以在文档头部说明下与 antd Tooltip 的差异:

![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/4f91198f-5503-4770-8dc3-c519a4b5cfdd)

2023-08-01 03:21 UTC, dengfuping commented on packages/design/src/tooltip/index.tsx
> +import useToken from 'antd/lib/theme/useToken';
useToken 没有用到

2023-08-01 03:21 UTC, dengfuping commented on packages/design/src/tooltip/index.tsx
> +    const IconNode = closeIcon === true ? <CloseOutlined className={`${prefixCls}-close-icon`} onClick={handleCloseClick} /> : <span style={{ cursor: 'pointer' }} className={`${prefixCls}-close-icon`
`cursor: 'pointer'` 样式建议放 `${prefixCls}-close-icon` 类目样式里，尽量避免行内样式

2023-08-01 03:21 UTC, dengfuping commented on packages/design/src/tooltip/index.tsx
> +  const hasCloseIcon = !(closeIcon === false || closeIcon === null)
- 可以不对具体值判断，这样更通用些，可以覆盖其他的空值场景。

```diff
- const hasCloseIcon = !(closeIcon === false || closeIcon === null);
+ const hasCloseIcon = !!closeIcon;
```

2023-08-01 03:21 UTC, dengfuping commented on packages/design/src/tooltip/index.tsx
> +          setOpen(v)
- `open` 已经是受控的，可以不用处理 `onOpenChange`

2023-08-01 03:21 UTC, dengfuping commented on packages/design/src/tooltip/index.tsx
> +  const [open, setOpen] = React.useState(undefined);
- 需要接收外部传入的 open 属性对 `open` 进行受控，内部只有关闭时才 `setOpen(false);`

2023-08-01 03:24 UTC, dengfuping requested changes

2023-08-01 03:24 UTC, dengfuping commented on packages/design/src/tooltip/demo/basic.tsx
> +      <Tooltip title="This is prompt text" closeIcon={<CloseCircleTwoTone />} onClose={log}>
- `closeIcon` 和 `onClose` 属于新增能力，应该提供单独的 demo。
- 自定义的 `closeIcon` 可以成 `CloseCircleOutlined`，TwoTone 风格的看起来不太搭:

![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/435811e1-b007-473e-935f-abcd696efca2)

2023-08-01 05:37 UTC, linhf123 commented on packages/design/src/tooltip/index.tsx
> +          setOpen(v)
`onOpenChange` 是用来处理 tooltip 常驻的，设置了 `closeIcon` 后要点击 关闭图标 才能关闭，这里的交互逻辑我在想下

2023-08-01 05:39 UTC, linhf123 commented on packages/design/src/tooltip/index.tsx
> +  const [open, setOpen] = React.useState(undefined);
内部使用 `open` 接管 `Tooltip` 展示逻辑时，使用 `setOpen(false)` 后要么监听 `onOpenChange` 来设置 `setOpen(true)` 在下次触碰时打开，要么设置 `open` 为`undefined` 让 Tooltip 自己接管展示逻辑

2023-08-01 05:40 UTC, linhf123 commented on packages/design/src/tooltip/demo/basic.tsx
> +      <Tooltip title="This is prompt text" closeIcon={<CloseCircleTwoTone />} onClose={log}>
好的，这里 `Demo` 我重新完善一下

2023-08-01 05:41 UTC, linhf123 commented on packages/design/src/tooltip/index.tsx
> +      {closeTitle}
这块的布局我在看下怎么处理比较好

2023-08-01 05:41 UTC, linhf123 commented on packages/design/src/tooltip/index.md
> +| onClose | 关闭时的回调（可通过 e.preventDefault() 来阻止默认行为） | (e) => void | - | - |
好

2023-08-01 05:44 UTC, linhf123 commented on packages/design/src/tooltip/index.tsx
> +    const IconNode = closeIcon === true ? <CloseOutlined className={`${prefixCls}-close-icon`} onClick={handleCloseClick} /> : <span style={{ cursor: 'pointer' }} className={`${prefixCls}-close-icon`
当时想的是，引入 `cssinjs` 代码量挺多的，这里单独用了下就直接行内样式了，我改一下这里。不过就修改少量样式怎么做比较好，这个感觉可以讨论下

2023-08-03 06:01 UTC, dengfuping commented
可以合并下 master 分支，解决站点构建失败的问题

2023-08-06 10:45 UTC, linhf123 commented on packages/design/src/tooltip/demo/basic.tsx
> +      <Tooltip title="This is prompt text" closeIcon={<CloseCircleTwoTone />} onClose={log}>
![image](https://github.com/oceanbase/oceanbase-design/assets/32009993/6a4c81ba-3f32-4d45-b977-89eaf5ede9c9)
![image](https://github.com/oceanbase/oceanbase-design/assets/32009993/32eb1665-976a-42cc-9471-16d9940fc432)

2023-08-06 10:48 UTC, linhf123 commented on packages/design/src/tooltip/index.tsx
> +  const [open, setOpen] = React.useState(undefined);
内部不再维护 `open`, 使用 `open` 失控时要配合 `onOpenChange` 进行打开，默认情况下设置 `closeIcon` 只做展示使用，不存在功能。内部维护一个 `open` 会有部分场景冲突，可以后续讨论下怎么交互比较合理

2023-08-06 10:49 UTC, linhf123 commented
> 可以合并下 master 分支，解决站点构建失败的问题

合并了 master 看起来构建还是有点问题

2023-08-20 17:21 UTC, linhf123 commented
参考 antd 的实现，修改了 dumi 样式文件，自定义了一下类型这列的样式
![image](https://github.com/oceanbase/oceanbase-design/assets/32009993/9ff2c890-8b35-4f82-bc0b-5262140adaa7)

2023-08-27 16:00 UTC, linhf123 commented
本地写了个测试用例跑了下，ConfigProvider 报了一个 antd 弃用的错误, 看起来直接删除就可以
![image](https://github.com/oceanbase/oceanbase-design/assets/32009993/46f68614-d565-4ee2-ac35-c833bc60388a)

2023-08-30 07:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oceanbase/oceanbase-design?pullRequest=63) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/oceanbase/oceanbase-design?pullRequest=63) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: linhf123<br/>:x: linhf<br/><hr/>**linhf** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oceanbase/oceanbase-design?pullRequest=63) it.</sub>

2023-08-30 07:43 UTC, linhf123 commented on packages/design/src/tooltip/__tests__/index.test.tsx
> +    jest.useRealTimers();
使用 waitFakeTimer 还必须带上这几句代码

2023-09-05 13:34 UTC, merged