fix(Tag):   The ellipsis with icons should work
oceanbase/oceanbase-design pull request #687
Opened 2024-08-30 08:48 UTC by linhf123

### 📦 Modified package

- [x] @oceanbase/design
- [ ] @oceanbase/ui
- [ ] @oceanbase/icons
- [ ] @oceanbase/charts
- [ ] @oceanbase/util
- [ ] @oceanbase/codemod
- [ ] Other (about what?)

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

1. Icon with ellipsis is abnormal for tag

| Before | After |
| :--- | :--- |
| ![image](https://github.com/user-attachments/assets/8d93876f-813c-42ca-9252-9bbb3f6f0695)|![image](https://github.com/user-attachments/assets/d8706dc4-e34b-40f5-8a9e-49672ed8342c)|

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Typography uses custom Icon in the case of ellipsis        |
| 🇨🇳 Chinese |    Typography 省略情况下使用自定义 Icon       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Tests is updated/provided or not needed
- [ ] Changelog is provided or not needed

2024-09-02 03:42 UTC, dengfuping requested changes

2024-09-02 03:42 UTC, dengfuping commented on packages/design/src/tag/index.tsx
> +            {realIcon}
icon 在 Tag 和 Typography 内都有设置，是特意的吗？原因是什么呢？

2024-09-02 03:42 UTC, dengfuping commented on packages/design/src/tag/index.tsx
> +    const realIcon = icon ? <span style={{ marginRight: 7 }}>{icon}</span> : null;
antd 7px 的计算逻辑，可以参考下，尽量不写死

https://github.com/ant-design/ant-design/blob/master/components/tag/style/index.ts#L35

2024-09-03 02:37 UTC, linhf123 commented on packages/design/src/tag/index.tsx
> +            {realIcon}
主要是为了使用 Typography 的 ellipsis，Typography.Text 内部会判断是否超出宽度来展示 tooltip，看了下对应的实现逻辑，自己来实现溢出之后展示 Tooltip 有点麻烦，所以将 Icon 包进去展示进行绕过

2024-09-03 02:40 UTC, linhf123 commented on packages/design/src/tag/index.tsx
> +    const realIcon = icon ? <span style={{ marginRight: 7 }}>{icon}</span> : null;
ok，这里我改一下

2024-09-03 13:01 UTC, dengfuping commented on packages/design/src/tag/index.tsx
> +            {realIcon}
OK，补下注释吧，属于特殊逻辑

2024-09-03 13:02 UTC, dengfuping commented
CI 挂了，需要重新拉取下 master 代码

2024-09-04 11:53 UTC, dengfuping requested changes

2024-09-04 11:53 UTC, dengfuping commented on packages/design/src/tag/index.tsx
> +            {realIcon}
这里应该是 `{ ellipsisConfig ? realIcon : null }` 吧，即有 ellipsis 配置时，将 icon 挪到 Typography 内部

2024-09-04 11:53 UTC, dengfuping commented on packages/design/src/tag/index.tsx
> +    const realIcon = icon ? <span className="inner-icon">{icon}</span> : null;
这里需要改为 Tag icon 的类名

2024-09-05 02:27 UTC, linhf123 commented on packages/design/src/tag/index.tsx
> +            {realIcon}
这个 ellipsisConfig 的配置，外层已经包了
![image](https://github.com/user-attachments/assets/b9193ad7-6e07-4faa-bc2f-33533fc4ede6)

2024-09-05 02:50 UTC, linhf123 commented on packages/design/src/tag/index.tsx
> +    const realIcon = icon ? <span className="inner-icon">{icon}</span> : null;
已修改

2024-09-05 07:21 UTC, merged