fix(ui): [date-ranger] fix desgin acceptance
oceanbase/oceanbase-design pull request #885
Opened 2024-12-12 08:53 UTC by wzc520pyfm

### 📦 Modified package

- [ ] @oceanbase/design
- [x] @oceanbase/ui
- [ ] @oceanbase/icons
- [ ] @oceanbase/charts
- [ ] @oceanbase/util
- [ ] @oceanbase/codemod
- [ ] Other (about what?)

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Tests is updated/provided or not needed
- [x] Changelog is provided or not needed

2024-12-12 08:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oceanbase/oceanbase-design?pullRequest=885) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/oceanbase/oceanbase-design?pullRequest=885) before we can accept your contribution.<br/><hr/>**王志超** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oceanbase/oceanbase-design?pullRequest=885) it.</sub>

2024-12-13 02:53 UTC, wzc520pyfm commented
@linhf123 国际化和选错时间交互也需要补充在这里

2024-12-13 09:44 UTC, dengfuping requested changes

2024-12-13 09:44 UTC, dengfuping commented on packages/ui/src/DateRanger/Ranger.tsx
> +                        isCn ? YEAR_DATE_TIME_SECOND_FORMAT_CN : YEAR_DATE_TIME_SECOND_FORMAT
日期时间格式在 locale 里有定义，可以直接使用，不用单独定义，可以参考 demo https://design.oceanbase.com/components/date-picker#packages-design-src-date-picker-demo-global-format

2024-12-13 09:44 UTC, dengfuping commented on packages/ui/src/DateRanger/index.less
> +  min-width: 1120px;
最小宽度为 1120px 的原因是什么呢？

2024-12-14 11:01 UTC, merged