fix(DateRanger): Add the internationalization of internal copywriting
oceanbase/oceanbase-design pull request #903
Opened 2024-12-23 06:55 UTC by linhf123

### 📦 Modified package

- [ ] @oceanbase/design
- [x] @oceanbase/ui
- [ ] @oceanbase/icons
- [ ] @oceanbase/charts
- [ ] @oceanbase/util
- [ ] @oceanbase/codemod
- [ ] Other (about what?)

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

### 📝 Changelog

![image](https://github.com/user-attachments/assets/c5525b34-fbc7-4da7-97fb-4b7dc07b92b2)
![image](https://github.com/user-attachments/assets/ade05730-aa48-46b6-9d8b-6b09520aee23)

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |  快捷选项增加 enLabel ，用来兼容内部国际化，外部传入自定义 select 直接在 label 上做国际化即可        |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Tests is updated/provided or not needed
- [ ] Changelog is provided or not needed

2024-12-23 08:23 UTC, wzc520pyfm approved these changes

2024-12-25 03:31 UTC, dengfuping requested changes

2024-12-25 03:31 UTC, dengfuping commented on packages/ui/src/locale/zh-TW.ts
> +import zhTW from '@oceanbase/design/locale/zh-TW';
需要用之前的 es 路径，目前只有仓库内部支持 locale 路径，在其他项目里还不支持

2024-12-26 03:23 UTC, linhf123 commented on packages/ui/src/locale/zh-TW.ts
> +import zhTW from '@oceanbase/design/locale/zh-TW';
我改了下 dumi 的配置，让子路径前移 优先匹配就可以了

2024-12-26 07:52 UTC, dengfuping approved these changes

2024-12-26 07:53 UTC, merged