Badge  支持 Icon + 状态
oceanbase/oceanbase-design pull request #98
Opened 2023-08-17 09:04 UTC by Vanleehao

### Task Description
Badge  支持 Icon + 状态

### Solution Description

增大 dot  大小至 8px
支持 Icon + 状态

### Passed Regressions
状态点
![image](https://github.com/oceanbase/oceanbase-design/assets/28707076/378ac9a6-0929-4de5-a0fb-7027ad16cafd)
Icon + 状态
![image](https://github.com/oceanbase/oceanbase-design/assets/28707076/a7b9b0b3-70f7-420d-b67f-f505e5af0f04)
自定义状态
![image](https://github.com/oceanbase/oceanbase-design/assets/28707076/e2272d34-512f-465a-8ed8-fdf52c464d29)

### Upgrade Compatibility

### Other Information

### Release Note

2023-08-17 09:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oceanbase/oceanbase-design?pullRequest=98) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/oceanbase/oceanbase-design?pullRequest=98) before we can accept your contribution.<br/><hr/>**郝建国** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oceanbase/oceanbase-design?pullRequest=98) it.</sub>

2023-08-18 02:15 UTC, dengfuping commented
- 合并下 master 分支，解决 CI 失败的问题
- 需要按照 RFC 模板填写 PR 内容，可以参考 #97

2023-08-18 02:15 UTC, dengfuping commented
- commit 信息避免使用中文:

![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/cfe7ceb6-fbf4-4dab-9a45-10781a2ed4a6)

2023-08-21 06:21 UTC, dengfuping commented
RFC 中可以把设计文档里的一些设计说明放过来，比如场景定义、设计稿截图等

2023-08-21 07:20 UTC, Vanleehao commented
> RFC 中可以把设计文档里的一些设计说明放过来，比如场景定义、设计稿截图等

done，师兄帮忙处理一下 Warning 状态的icon，我替换下

2023-08-21 07:20 UTC, Vanleehao commented
> RFC 中可以把设计文档里的一些设计说明放过来，比如场景定义、设计稿截图等

done，师兄帮忙处理一下 Warning 状态的icon，我替换下

2023-08-21 07:33 UTC, dengfuping requested changes

2023-08-21 07:33 UTC, dengfuping commented on packages/design/src/badge/index.md
> +- 💄 定制主题和样式，符合 OceanBase Design 设计规范。
加一条:
- 🆕 新增 `icon` 属性，支持状态图标。

2023-08-21 07:33 UTC, dengfuping commented on packages/design/src/badge/index.md
> +| icon | 状态标识是否为图标形势，传入true采用默认icon，传入Icon可自定义icon | boolean \| React.ReactNode | false  | -    |
中英文之间使用空格，建议改为:

是否为状态图标，`status` 不为空时生效。值为 `true` 时展示默认状态图标，值为 `ReactNode` 时展示自定义状态图标

2023-08-21 07:33 UTC, dengfuping commented on packages/design/src/badge/index.md
> +<code src="./demo/icon.tsx" title="自定义 Icon"></code>
```diff
- <code src="./demo/icon-badge.tsx" title="Icon + 状态" description="用 icon 标识状态"></code>
- <code src="./demo/icon.tsx" title="自定义 Icon"></code>
+ <code src="./demo/status-icon.tsx" title="状态图标" description="使用图标标识状态，增强感知"></code>
+ <code src="./demo/status-customize-icon.tsx" title="自定义状态图标"></code>
```

2023-08-21 07:33 UTC, dengfuping commented on packages/design/src/badge/style/index.ts
> +  badgeDotSizeLG: number;
- TS 类型首字母大写: `badgeToken` => `badgeToken `
- `badgeDotSize` 这些类型没有用到，可以去掉。

2023-08-21 07:33 UTC, dengfuping commented on .dumirc.ts
> +  // monorepoRedirect: {},
这个配置不需要修改吧

2023-08-21 07:33 UTC, dengfuping commented on .vscode/settings.json
> +    "editor.defaultFormatter": "vscode.typescript-language-features"
这里的配置不需要修改吧，有 `"editor.defaultFormatter": "esbenp.prettier-vscode",` 配置就能涵盖大部分文件的格式化了，应该不用针对特定文件配置。

2023-08-21 07:33 UTC, dengfuping commented on packages/design/src/badge/style/index.ts
> +  const badgeDotHight = 8;
- 宽高都是一样的值，定义为 `badgeDotSize` 即可
- antd 的 badgeDotSize 并不是写死的，而是根据 `fontSizeSM` 字体大小计算而来 https://github.com/ant-design/ant-design/blob/b50928fb88946783258960f0f8f1d59a4028541e/components/badge/style/index.ts#L354，这样可以适应更多的场景，只不过 OB 侧是根据 `fontSizeLG` 计算而来。

```diff
- const badgeDotSize = fontSizeSM / 2;
+ const badgeDotSize = fontSizeLG / 2;
```

2023-08-21 07:33 UTC, dengfuping commented on packages/design/src/badge/index.tsx
> +Badge.Icon = IconBadge;
- IconBadge 属于内部组件，不需要导出
- 反倒是 Ribbon 需要挂载到 Badge 上，不然无法兼容 antd

```ts
Badge.Ribbon = AntBadge.Ribbon;
```

2023-08-21 07:33 UTC, dengfuping commented on packages/design/src/badge/style/index.ts
> +      width: 12,
- 应该使用 `fontSizeSM` 作为图标大小，值尽量不写死。
- icon 应该是通过 `fontSize` 设置大小吧，如果要考虑自定义 icon 为 图片，也可以同时设置 `fontSize` 和 `height`。

2023-08-21 07:33 UTC, dengfuping commented on packages/design/src/badge/style/index.ts
> +      [`&-oceanbase`]: genIconStyle(token)
- genSizeStyle 和 genIconStyle 只用到一次，没有必要抽成函数，裸写样式即可
- 去掉 `oceanbase` 的类名，没有意义

2023-08-21 07:33 UTC, dengfuping commented on packages/design/src/badge/index.tsx
> +      [`${prefixCls}-oceanbase-gray`]: gray,
去掉 `oceanbase` 的类名，没有意义

2023-08-21 07:33 UTC, dengfuping commented on packages/design/src/badge/index.tsx
> +  gray?: boolean;
去掉 gray 属性，没有用到

2023-08-21 07:33 UTC, dengfuping commented on packages/design/src/badge/index.tsx
> +      />
- 判断条件应该是: `status && icon ? xxx : xxx`，status 不为空才展示位状态点。
- 其实可以不用新增 IconBadge 组件，如果是 icon 模式，只要在前面追加 icon dom，并且隐藏掉 dot dom 就可以，这样会更简单。

2023-08-21 07:34 UTC, dengfuping requested changes
需要针对 icon 补充下单测，包括 snapshots 快照

2023-08-21 07:36 UTC, dengfuping requested changes

2023-08-21 07:36 UTC, dengfuping commented on packages/design/src/badge/demo/icon.tsx
> +
多了一个空行

2023-08-21 07:44 UTC, dengfuping requested changes

2023-08-21 07:44 UTC, dengfuping commented on packages/design/src/badge/IconBadge.tsx
> +      statusIcon = <StopFilled />;
直接设置一个 map 对象即可，不用写 `if...else...`

```ts
const iconMap = {
  default: <StopFilled />,
  processing: <Loading3QuartersOutlined />,
 ...
};
```

2023-08-21 07:44 UTC, dengfuping commented on packages/design/src/badge/IconBadge.tsx
> +    statusIcon = icon
这里最好是判断 icon 为 ReactNode 时为自定义 icon，否则为默认 icon。比如对于 `icon={{}}`，仍然应该渲染默认 icon。

```ts
isValidElement(icon) ? 自定义 icon : 默认 icon
```

2023-08-21 07:52 UTC, dengfuping commented
> > RFC 中可以把设计文档里的一些设计说明放过来，比如场景定义、设计稿截图等
> 
> done，师兄帮忙处理一下 Warning 状态的icon，我替换下

OK，我加完 icon 后同步给你

2023-08-23 06:28 UTC, dengfuping requested changes
还有问题未修复

2023-08-23 06:28 UTC, dengfuping commented on packages/design/src/badge/IconBadge.tsx
> +  const statusTextNode = !text ? <></> : <span className="ant-badge-status-text">{text}</span>;
`ant-badge` 不能写死

2023-09-20 05:59 UTC, dengfuping commented
- 先合并一版，实现细节后续再做优化

2023-09-20 05:59 UTC, dengfuping approved these changes

2023-09-20 05:59 UTC, merged